### hello rest 
GET http://localhost:8080/api/v2/fc
Content-Type: application/octet-stream
auth-token : DtqBzT4O

### file list
GET http://localhost:8080/api/v2/fc/filelist?cwd=./
auth-token : DtqBzT4O

### Post test 바이너리 (raw) 바디파서
POST http://localhost:8080/api/v1/write
write-name : test.bin
write-directory : ./uploads
Content-Type: application/octet-stream
auth-token : 5874

hello post body express

### Post write text ,텍스프 바디파서 
POST http://localhost:8080/api/v1/write
write-name : test.txt
write-directory : ./uploads
Content-Type: text/plain
auth-token : 5874

hello express post body text parser 

### Post read file , json 바디 파서 
POST http://localhost:8080/api/v1/read
Content-Type: application/json
auth-token : 5874

{"path":"./uploads","file":"test.txt"}

### challenge intro 
GET http://localhost:8080/api/v2/challenge
Content-Type: text/plain
auth-token : DtqBzT4O


### challenge register
GET http://localhost:8080/api/v2/challenge/register?name=이석준&studentId=60695&passwd=1234
Content-Type: text/plain
auth-token : DtqBzT4O

### start hl game 
GET http://localhost:8080/api/v2/challenge/start_hl?studentId=60695&passwd=1234
Content-Type: text/plain
auth-token : DtqBzT4O

### find hl game
GET http://localhost:8080/api/v2/challenge/find_hl?studentId=60695&passwd=1234&num=8765
Content-Type: text/plain
auth-token : DtqBzT4O

### record list
GET http://localhost:8080/api/v2/challenge/get_hl_record
Content-Type: text/plain
auth-token : DtqBzT4O

### clear list
GET http://localhost:8080/api/v2/challenge/clear
Content-Type: text/plain
auth-token : DtqBzT4O


### sample root call
GET http://localhost:8080/api/v2/sample
Content-Type: text/plain
auth-token : DtqBzT4O

### sample add
GET http://localhost:8080/sample/add?a=1&b=2
Content-Type: text/plain
